steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/discord-line-bot', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-line-bot']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'discord-line-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/discord-line-bot'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DISCORD_BOT_TOKEN=${_DISCORD_BOT_TOKEN},LINE_CHANNEL_ACCESS_TOKEN=${_LINE_CHANNEL_ACCESS_TOKEN},LINE_TARGET_GROUP_ID=${_LINE_TARGET_GROUP_ID}'

images:
  - 'gcr.io/$PROJECT_ID/discord-line-bot'

substitutions:
  _DISCORD_BOT_TOKEN: '你的DiscordBotToken'
  _LINE_CHANNEL_ACCESS_TOKEN: '你的LineChannelToken'
  _LINE_TARGET_GROUP_ID: '接收LINE訊息的groupId'

options:
  logging: CLOUD_LOGGING_ONLY